// <auto-generated />
using System;
using KindergartenApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KindergartenApp.Migrations
{
    [DbContext(typeof(KindergartensDbContext))]
    [Migration("20200706121823_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KindergartenApp.Models.Child", b =>
                {
                    b.Property<long>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<string>("Characterization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChildrenGroup")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Height")
                        .HasColumnType("bigint");

                    b.Property<long>("KindergartenID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ChildId");

                    b.HasIndex("KindergartenID");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("KindergartenApp.Models.Kindergarten", b =>
                {
                    b.Property<long>("KindergartenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<string>("KindergartenName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KindergartenId");

                    b.ToTable("Kindergartens");
                });

            modelBuilder.Entity("KindergartenApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KindergartenApp.Models.UserKindergarten", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("KindergardenId")
                        .HasColumnType("bigint");

                    b.Property<long?>("KindergartenId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("UserId", "KindergardenId");

                    b.HasIndex("KindergartenId");

                    b.HasIndex("UserId1");

                    b.ToTable("UserKindergartens");
                });

            modelBuilder.Entity("KindergartenApp.Models.Child", b =>
                {
                    b.HasOne("KindergartenApp.Models.Kindergarten", "Kindergarten")
                        .WithMany("Children")
                        .HasForeignKey("KindergartenID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KindergartenApp.Models.UserKindergarten", b =>
                {
                    b.HasOne("KindergartenApp.Models.Kindergarten", "Kindergarten")
                        .WithMany("UserKindergartens")
                        .HasForeignKey("KindergartenId");

                    b.HasOne("KindergartenApp.Models.User", "User")
                        .WithMany("UserKindergatens")
                        .HasForeignKey("UserId1");
                });
#pragma warning restore 612, 618
        }
    }
}
